research_task:
  description: >
    Research the user's query: {query}
    
    ## Step 1: Choose the Right Tool
    
    **ExaAnswerTool (exa_answer)**: For specific, factual questions
    - Example: "What is the capital of France?", "Who won the last World Cup?"
    - Returns: Direct answer with citations (formatted text)
    
    **ExaSearchTool (exa_web_search)**: For complex research or open-ended questions
    - Example: "Latest AI developments", "How to cook eggs in air fryer?"
    - Returns: JSON string with search results already formatted as SourceInfo objects
    
    When in doubt, use ExaSearchTool for comprehensive coverage.
    
    ## Step 2: Parse the Tool Results
    
    **ExaSearchTool returns JSON** in this format:
    ```json
    {
      "query": "...",
      "num_results": 5,
      "results": [
        {
          "url": "https://...",
          "title": "...",
          "image_url": null,
          "snippet": "..."
        }
      ]
    }
    ```
    
    The "results" array is already in SourceInfo format - you can use it directly!
    Extract the key information from snippets to write your summary.
    
    ## Step 3: Create Your Output
    
    Write a 2-3 paragraph summary based on the search result snippets.
    Use the "results" array from the tool output as your "sources" field.
    DO NOT write explanatory text, thoughts, or meta-commentary.
  expected_output: >
    A ResearchResult object with three fields: summary, sources, and citations.
    
    CRITICAL OUTPUT FORMAT RULES:
    
    1. DO NOT include your thinking process, reasoning, or explanations
    2. DO NOT write "Thought:" or "I will..." statements
    3. DO NOT write narrative text before the JSON structure
    4. Return ONLY the structured data in the correct format
    
    ## Field Requirements:
    
    **summary** (string): 
    A concise 2-3 paragraph summary of the key findings from search results.
    Write clear, factual sentences. No meta-commentary.
    
    **sources** (array of objects):
    Extract 5-8 most relevant sources from search results.
    Each source MUST be an object with ALL four fields:
    
    ```
    {
      "url": "https://example.com",           # required: source URL
      "title": "Article Title",                # required: use "Unknown" if missing
      "image_url": null,                       # required: use null if no image
      "snippet": "Brief description..."        # required: use "" if no snippet
    }
    ```
    
    CRITICAL: Every source object MUST have all 4 fields. Use null or "" for missing data.
    
    **citations** (array of strings):
    List of source URLs that were directly cited in the summary.
    Example: ["https://example.com", "https://another.com"]
    
    ## What Good Output Looks Like:
    
    summary: "Microsoft announced Copilot Mode for Edge browser on October 24, 2025. The feature includes autonomous actions..."
    
    sources: [
      {
        "url": "https://daily-ai.info/",
        "title": "Daily AI Insight",
        "image_url": null,
        "snippet": "Microsoft launches Copilot Mode in Edge..."
      }
    ]
    
    citations: ["https://daily-ai.info/"]
    
    ## What BAD Output Looks Like (DO NOT DO THIS):
    
    ❌ "Thought: I will now synthesize..."
    ❌ "Based on the search results, I found..."
    ❌ Writing explanation before the data structure
    ❌ Missing fields in source objects
    ❌ Empty image_url fields without null value
  agent: researcher_agent
