research_task:
  description: >
    Research and provide comprehensive information about the user's query: {query}.
    You have access to TWO different tools - choose the most appropriate one:

    **ExaAnswerTool (exa_answer)**: Use for specific, factual questions that need quick, direct answers.
    - Best for: "What is the capital of France?", "What is the latest SpaceX valuation?", "Who won the last World Cup?"
    - Returns: Direct answer with citations
    - Parameter: Use "query": "your question" when calling the tool

    **ExaSearchTool (exa_web_search)**: Use for complex research, open-ended questions, or when you need multiple sources.
    - Best for: "What is the state of AI in healthcare?", "How to cook eggs in air fryer?", "Latest developments in renewable energy"
    - Returns: Multiple search results with detailed content
    - Parameter: Use "query": "your search terms" when calling the tool

    IMPORTANT: be fast! Users expect a professional response as fast as possible.
    
    Choose the tool based on the query type:
    - Simple factual questions → Use ExaAnswerTool
    - Complex research topics → Use ExaSearchTool
    - When in doubt, use ExaSearchTool for comprehensive coverage
    
    Analyze the results and synthesize the findings into a clear, well-structured response.
    Include relevant citations and sources when available.
    
    IMPORTANT: When creating your sources, extract image URLs from the raw search data.
    The news results especially contain imageUrl fields that you should include in your SourceInfo objects.
    
    For each source, make sure to include:
    - url: the source URL
    - title: the source title  
    - image_url: extract from imageUrl field in search results (if available)
    - snippet: the source snippet
    
    Look for imageUrl fields in the organic search results, knowledge graph, and news results.
    News results are particularly good for finding images.
  expected_output: >
    A comprehensive, well-structured answer that addresses the user's query with:
    - Clear and accurate information
    - Current data and insights
    - Relevant sources with metadata (URL, title, image URL, snippet)
    - Organized presentation of findings
    - sources should be mapped to the information they provide in the response, when possible.
    - Include image URLs from search results to provide visual context
    - Combine results from both search and news tools for comprehensive coverage
    
    CRITICAL: You MUST return sources as a JSON array of objects, NOT as strings.
    
    WRONG FORMAT (will cause errors):
    sources: ["https://example.com", "https://another.com"]
    
    CORRECT FORMAT:
    sources: [
      {
        "url": "https://example.com",
        "title": "Example Title",
        "image_url": "https://example.com/image.jpg", 
        "snippet": "Brief description"
      },
      {
        "url": "https://another.com",
        "title": "Another Title",
        "image_url": null,
        "snippet": "Another description"
      }
    ]
    
    Each source MUST be an object with these exact fields:
    - url (required): the source URL
    - title (optional): the source title
    - image_url (optional): image URL if available
    - snippet (optional): brief description
  agent: researcher_agent
